# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b896bc9da90a121bd01e820fb74fb587ade96d797fb50ea9e1fb25ba5c39915060f06c2d06b019efc6f25e6c2b017dea693d633d60243e8dc64d2cb014af5fc

test:
  secret_key_base: fcebc4699b158e1cb50afc4042c2a692ba93bbed155e1f8a0815623aa94f59952cde5b03e3ea340d4c06ef215b766a2b17bb91c453be987aaf07c0aeed8b8257

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
